apiVersion: v1
kind: Service
metadata:
  name: mailfind-backend
  namespace: mailfind
  labels:
    app: mailfind
    component: backend
spec:
  type: ClusterIP
  selector:
    app: mailfind
    component: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

